# 1. Array

To call Numpy module, import `numpy` as `np`
Create 1-dimentional vector with name 'test_array' as following.

In [ ]:
import numpy as np
test_array = np.array([1,4,5,8], float)
print(test_array)

[1. 4. 5. 8.]


In [ ]:
print(type(test_array))
print(type(test_array[3]))

<class 'numpy.ndarray'>
<class 'numpy.float64'>


Various Slicing

In [ ]:
import numpy as np
a = np.array([[1,2,3,4,5],[6,7,8,9,10]], int)
b = a[:,2:]
print(b)

[[ 3  4  5]
 [ 8  9 10]]


In [ ]:
c = a[1,1:3]
print(c)

[7 8]


In [ ]:
d = a[1:]
print(d)

[[ 6  7  8  9 10]]


In [ ]:
print(a[0:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Create an array (1 by 30 vector) containing 30 integers from 0 to 29

In [ ]:
a = np.arange(30)
print(a)
print(type(a))
print(a.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
<class 'numpy.ndarray'>
int64


Reshape the vector to a 5 by 6 matrix

In [ ]:
print(a.reshape(5,6))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


# 2. Operations
Array (Matrix) Operations between matrices

In [ ]:
test_a = np.array([[1,2,3],[4,5,6]], float)
print(test_a + test_a)
print(test_a - test_a)
print(test_a.transpose())
print(test_a * test_a)
print(test_a.T.dot(test_a))

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[17. 22. 27.]
 [22. 29. 36.]
 [27. 36. 45.]]


Array Operations between a matrix and a scalar

Visit <https://realpython.com/python-operators-expressions/>

In [ ]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 5
print(test_matrix + scalar)
print(test_matrix - scalar)
print(test_matrix * scalar)
print(test_matrix / scalar)
print(test_matrix // 0.2)
print(test_matrix ** 2)

[[ 6.  7.  8.]
 [ 9. 10. 11.]]
[[-4. -3. -2.]
 [-1.  0.  1.]]
[[ 5. 10. 15.]
 [20. 25. 30.]]
[[0.2 0.4 0.6]
 [0.8 1.  1.2]]
[[ 4.  9. 14.]
 [19. 24. 29.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]


# 3. Linear Algebra

In [ ]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])
x = np.linalg.solve(a,b)
print(x)

[2. 3.]
